[package]
name = "connect4"
version = "0.1.0"
authors = ["Vincent Junge <vincentjunge@posteo.net>"]
edition = "2018"

[dependencies]
smallvec = "1"
oorandom = "11"
getrandom = "0.2"
rayon = "1.5"
structopt = "0.3"